export const SITE = {
  website: "https://jinergenkai.github.io/",
  author: "Nguyễn Mạnh Hùng",
  profile: "https://github.com/jinergenkai",
  desc: "Senior Backend Engineer | Viết về Java, System Design, DevOps và những gì tôi học được.",
  title: "Nguyễn Mạnh Hùng",
  ogImage: "og-default.png",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000, // 15 minutes
  showArchives: true,
  showGalleries: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Chỉnh sửa bài viết",
    url: "https://github.com/jinergenkai/jinergenkai.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "vi",
  timezone: "Asia/Ho_Chi_Minh",
  introAudio: {
    enabled: true,
    src: "/audio/intro-web.mp3",
    label: "INTRO.MP3",
    duration: 30,
  },
} as const;
